services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:123@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
